### ISSUE TITLE
Update CAPO CLI Flags

### ISSUE THREAD

**Issue by spjmurray** [unikorn-cloud/helm-cluster-api#9]
```
Flag --metrics-bind-addr has been deprecated, Please use --diagnostics-address instead. To continue to servemetrics via http and without authentication/authorization set --insecure-diagnostics as well.
```

**Comment by spjmurray** [comment]
Note this is just CAPO being behind the times.  There are new values:

```yaml
cluster-api-core:
  capi_diagnostics_address: :8443
  capi_insecure_diagnostics: false
```

for all other components.  We should consider altering the script to make these use `.Values.global` variables to set them in one place.
